version: '3'
services:
  modbus2mqtt:
    container_name: modbus2mqtt
    image: modbus2mqtt/server
    restart: unless-stopped
    user: ${UID}
    ports:
      - ${PORT_MODBUS2MQTT}:3000/tcp
    environment:
      - TZ=Europe/Brussels
      - MODBUS2MQTT_CONFIG_URL="http://${HOSTNAME}:${PORT_MODBUS2MQTT}"
      - DEBUG=httpserver config
    volumes:
      - ${PWD}/modbus2mqtt/data:/data
      - ${PWD}/modbus2mqtt/ssl:/ssl
      - /run/udev:/run/udev:ro
    devices:
      - ${DEVICE_MODBUS}:/dev/ttyACM0
    group_add:
      - dialout #docker group id
