name: Run E2E tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    environment: release
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install modules
        run: npm install .
      - name: build modbus2mqtt server
        run: npx tsc
      - name: Run tests
        run: npm test
      - name: 'Check localdev existance'
        id: check_localdev
        uses: andstor/file-existence-action@v2
        with:
          files: './e2e/localdev.sh'
      - name: Packages and system services for e2e Tests
        if: steps.check_localdev.outputs.files_exists == 'true'
        run: ./e2e/localdev.sh root
      - name: Local services for e2e Tests
        if: steps.check_localdev.outputs.files_exists == 'true'
        run: ./e2e/localdev.sh        
      - name: Cypress run
        if: steps.check_localdev.outputs.files_exists == 'true'
        uses: cypress-io/github-action@v6
