name: Run E2E tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened,synchronize edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    environment: release
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install modules
        run: npm install .
      - name: build modbus2mqtt server
        run: npx tsc
      - name: Run tests
        run: npm test
      - name: Packages and system services for e2e Tests
        run: ./cypress/servers/installPackages
      - name: Local services for e2e Tests
        run: ./cypress/servers/startRunningServers
      - name: Cypress run
        uses: cypress-io/github-action@v6
