name: On close pull request: deploy to dockerhub
on:
 pull_request:
    types:
      - closed
 workflow_dispatch:
jobs:
  updateHassio:
    name: "Publish Addon"
    uses: modbus2mqtt/server/.github/workflows/publishDocker.yml@main
    permissions:
      contents: write
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT: ${{ secrets.PAT }}
    
     
