name:  Publish NPM, Dockerfile and Addon
on:
  push:
    tags:
      - "v*"
  workflow_call:
jobs:
  release:
    name: "Publish to NPM and release in github"
    uses: modbus2mqtt/specification.shared/.github/workflows/publish.yml@main
    permissions:
      contents: write
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  releaseDocker:
    needs: release
    name: "Publish to Docker and Addon"
    uses: modbus2mqtt/server/.github/workflows/publishDocker.yml@main
    permissions:
      contents: write
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT: ${{ secrets.PAT }}
