on:
  push:
    tags:
      - "v*"
jobs:
  release:
    uses: modbus2mqtt/specification.shared/.github/workflows/publish.yml@main
    permissions:
      contents: write
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Check out server
        uses: actions/checkout@v4
        with:
          path: 'server'
      - name: Check out hassio-addon-repository
        uses: actions/checkout@v4
        with:
          path: 'hassio-addon-repository'
          repository: 'modbus2mqtt/hassio-addon-repository'
      - name: Prepare Addon Directory
        run: |
         chmod +x ./server/docker/releaseAddon.py
         ./server/docker/releaseAddon.py --release
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ./hassio-addon-repository/modbus2mqtt \
            --docker-hub modbus2mqtt
        
    

  
