name:  Publish Dockerfile and Addon

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      PAT:
        required: true
permissions:
  contents: write
jobs:
  publish:
    name: "Publish to Docker and Addon"
    runs-on: ubuntu-latest
    environment: release
    env:
      TAG_NAME: "declaration"
    steps:
      - name: Check out server
        uses: actions/checkout@v4
        with:
          path: 'server'
          token: ${{ secrets.PAT }}
      - name: Check out hassio-addon-repository
        uses: actions/checkout@v4
        with:
          path: 'hassio-addon-repository'
          repository: 'modbus2mqtt/hassio-addon-repository'
          ref: '${GITHUB_HEAD_REF}'
          token: ${{ secrets.PAT }}
      - name: Prepare Addon Directory
        id: prepareAddonDirectory
        run: |
         chmod +x ./server/docker/releaseAddon.py 
         ./server/docker/releaseAddon.py --release >>$GITHUB_ENV
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: hassio-addon-repository/modbus2mqtt/CHANGELOG.md
      - name: Checkin hassio-addon-repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./hassio-addon-repository
          tagging_message: ${{env.TAG_NAME}}
          commit_message: ${{env.TAG_NAME}}         
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/release'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        if: github.ref == 'refs/heads/release'
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ./hassio-addon-repository/modbus2mqtt/ \
            --image modbus2mqtt-{arch} \
            --docker-hub modbus2mqtt
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1        
        with:
          path: server
      - name: Publish Multiplatform  
        if: github.ref == 'refs/heads/release'
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: modbus2mqtt/modbus2mqtt:${{ steps.package-version.outputs.current-version}}
          images: modbus2mqtt/modbus2mqtt-aarch64:${{ steps.package-version.outputs.current-version}},modbus2mqtt/modbus2mqtt-amd64:${{ steps.package-version.outputs.current-version}},modbus2mqtt/modbus2mqtt-armv7:${{ steps.package-version.outputs.current-version}}
          push: true

        
    

  
