name:  Test variables

on:
  pull_request:
    types: [opened, reopened]
permissions:
  contents: write
jobs:
  test:
    name: "Test pull request"
    uses: modbus2mqtt/specification.shared/.github/workflows/test.yml@main
