name:  Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      PAT:
        required: true
permissions:
  contents: write
jobs:
  publish:
    name: "Publish to Docker and Addon"
    runs-on: ubuntu-latest
    environment: release
    env:
      TAG_NAME: "declaration"
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish Multiplatform  
      uses: int128/docker-manifest-create-action@v2
      with:
        tags: |
          modbus2mqtt/modbus2mqtt:${{env.TAG_NAME}}
        sources: |
          modbus2mqtt/modbus2mqtt-aarch64:${{env.TAG_NAME}}
          modbus2mqtt/modbus2mqtt-amd64:${{env.TAG_NAME}}
          modbus2mqtt/modbus2mqtt-armv7:${{env.TAG_NAME}}
          
        
    

  
