name: Update package.json
on:
 pull_request:
    types:
      - closed
 workflow_dispatch:
jobs:
  updatepkgjson:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    environment: release
    name: 'Update package.json'
    steps:
      - uses: actions/checkout@v4
        if: github.event.pull_request.merged == true
      - name: Set up Node.js
        if: github.event.pull_request.merged == true
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install modules
        if: github.event.pull_request.merged == true
        run: |
          npm install --package-lock-only github:specification.shared github:specification \
          github:modbus2mqtt/server.sharedgithub:modbus2mqtt/angular
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.event.pull_request.merged == true
  updateHassio:
    needs: updatepkgjson
    name: "Publish Addon"
    uses: modbus2mqtt/server/.github/workflows/publishDocker.yml@main
    permissions:
      contents: write
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PAT: ${{ secrets.PAT }}
    
     
